### ISSUE TITLE
Bartender4 functionality possible?

### ISSUE THREAD

**Issue by jonomurphy** [SiarkowyMods/TotemTwist#1]
Not an issue, per se, but I was wondering if this could be made to work with Bartender4? I tried playing around with the LUA myself but to no avail.

https://github.com/UndercityAddons-TBC/Bartender4

**Comment by Siarkowy** [comment]
Hello, I added support for Bartender 4. Please test with https://github.com/SiarkowyMods/TotemTwist/archive/bacfd43140cb0c528f6ca26fa562590bc5e63eb7.zip and let me know if it works for you.

**Comment by jonomurphy** [comment]
Hi there,

I installed it, but I don't seem to see any icon, nor do I see anything in /bt options.
Where does the icon usually go by default, i.e. which actionbar?

Cheers

**Comment by jonomurphy** [comment]
Actually it does work! Thanks a lot!

**Comment by Siarkowy** [comment]
Glad it works. Enjoy!
